### ISSUE TITLE
Error: spawn EACCES error - V0.1.16

### ISSUE THREAD

**Issue by codeuniquely** [RoccoC/webpack-build-notifier#18]
Mac OS Sierra 10.12.6
Webpack 1.13.2

When building the project - get the following error
(everything was building fine - and using notifications v0.1.14 in the project)  

Also project builds fine if I remove the Notifier plugin from webpack config......

```
internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Object.exports.execFile (child_process.js:143:15)
    at Object.module.exports.fileCommand (/Users/Projects/contact/node_modules/node-notifier/lib/utils.js:53:13)
    at NotificationCenter.notify (/Users/Projects/contact/node_modules/node-notifier/notifiers/notificationcenter.js:66:11)
    at WebpackBuildNotifierPlugin.onCompilationDone (/Users/Projects/contact/node_modules/webpack-build-notifier/index.js:152:18)
    at Compiler.applyPlugins (/Users/Projects/contact/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/Projects/contact/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> npm ERR! code ELIFECYCLE
```

**Comment by RoccoC** [comment]
Thanks for the report. Looks to be related to https://github.com/mikaelbr/node-notifier/issues/199.

What version of NPM are you using? Can you try upgrading to npm v5.4.1 and reinstalling your node_modules?

**Comment by codeuniquely** [comment]
cheers - that did the trick - 

upgrading to V5.4.1 (from V5.4.0) worked ...

Thanks
