### ISSUE TITLE
ENAMETOOLONG on Windows

### ISSUE THREAD

**Issue by sgehrman** [RoccoC/webpack-build-notifier#20]
This has been working great for a while, but now getting this:

using electron-webpack, all packages are updated

Error: spawn ENAMETOOLONG
      at _errnoException (util.js:1024:11)
      at ChildProcess.spawn (internal/child_process.js:323:11)
      at exports.spawn (child_process.js:502:9)
      at Object.exports.execFile (child_process.js:212:15)
      at Object.module.exports.fileCommand (f:\Github\eth-client\node_modules\node-notifier\lib\utils.js:53:13)
      at WindowsToaster.notify (f:\Github\eth-client\node_modules\node-notifier\notifiers\toaster.js:65:9)
      at WebpackBuildNotifierPlugin.onCompilationDone (f:\Github\eth-client\node_modules\webpack-build-notifier\index.js:172:18)
      at Compiler.applyPlugins (f:\Github\eth-client\node_modules\tapable\lib\Tapable.js:61:14)
      at Watching._done (f:\Github\eth-client\node_modules\webpack\lib\Compiler.js:104:17)
      at onCompiled (f:\Github\eth-client\node_modules\webpack\lib\Compiler.js:54:18)
      at applyPluginsAsync.err (f:\Github\eth-client\node_modules\webpack\lib\Compiler.js:514:14)
      at next (f:\Github\eth-client\node_modules\tapable\lib\Tapable.js:202:11)
      at Compiler.<anonymous> (f:\Github\eth-client\node_modules\webpack\lib\CachePlugin.js:78:5)
      at Compiler.applyPluginsAsyncSeries (f:\Github\eth-client\node_modules\tapable\lib\Tapable.js:206:13)
      at compilation.seal.err (f:\Github\eth-client\node_modules\webpack\lib\Compiler.js:511:11)
      at Compilation.applyPluginsAsyncSeries (f:\Github\eth-client\node_modules\tapable\lib\Tapable.js:195:46)
      at self.applyPluginsAsync.err (f:\Github\eth-client\node_modules\webpack\lib\Compilation.js:680:19)
      at Compilation.applyPluginsAsyncSeries (f:\Github\eth-client\node_modules\tapable\lib\Tapable.js:195:46)
      at self.applyPluginsAsync.err (f:\Github\eth-client\node_modules\webpack\lib\Compilation.js:671:11)
      at Compilation.applyPluginsAsyncSeries (f:\Github\eth-client\node_modules\tapable\lib\Tapable.js:195:46)
      at self.applyPluginsAsync.err (f:\Github\eth-client\node_modules\webpack\lib\Compilation.js:666:10)
      at next (f:\Github\eth-client\node_modules\tapable\lib\Tapable.js:202:11)

**Comment by RoccoC** [comment]
Thanks for the report.

I see you've found the related node-notifier issue (https://github.com/mikaelbr/node-notifier/issues/145), but I will see if there's anything I can do to debug this from my side.

**Comment by sgehrman** [comment]
Found out that if there is a large error it fails. I keep seeing this if git converts LF to CRLF then every CR is an error the linter and makes every line an error.

**Comment by RoccoC** [comment]
In that case, we could probably truncate/limit the error string to a max length before calling `notify()`. Will have a look today.

**Comment by RoccoC** [comment]
@sgehrman, can you please confirm your Windows version as well as the version of node-notifier that you have installed?

**Comment by RoccoC** [comment]
@sgehrman, this has been fixed in the latest version (0.1.18). Can you give it a go and let me know if it resolves your issue?

**Comment by sgehrman** [comment]
Thanks for looking at this.  I don't seem to see any notifications now, but it didn't crash like before.  I'll do some more testing to confirm, but check if it gives any notifications on Windows.

**Comment by sgehrman** [comment]
yeah, no messages now. I think this is wrong.

You changed it, but your change seems incorrect.

+WebpackBuildNotifierPlugin.prototype.defaultMessageFormatter = function(error, filepath) {
      return filepath + os.EOL + (error.message ? error.message.replace(error.module ? error.module.resource : '', '') : '');		      return filepath + os.EOL + (error.message ? error.message.replace(error.module ? error.module.resource : '', '') : '');
  };		  };

**Comment by RoccoC** [comment]
Hmm, I tested on Windows 10 Version 1703 (OS Build 15063.726) using node-notifier v5.1.2. Let me know if you are still having issues and whether your setup is different.

**Comment by sgehrman** [comment]
your last commit

**Comment by sgehrman** [comment]
I'm Windows Pro 1709 build 16299.64

**Comment by RoccoC** [comment]
OK, will investigate today.

**Comment by RoccoC** [comment]
@sgehrman, looks to be an issue with Windows build 1709: https://github.com/mikaelbr/node-notifier/issues/206

**Comment by sgehrman** [comment]
Ok. Good to know.

**Comment by RoccoC** [comment]
@sgehrman, I finally updated to Windows build 1709 (Fall Creator's Update) and was able to reproduce. The latest version of webpack-build-notifier (0.1.19) should now generate notifications in Windows. Can you please take a look and let me know if you are still having issues?

**Comment by sgehrman** [comment]
doesn't seem to work.  Maybe I'm just confused, I'll do some more tests.

**Comment by RoccoC** [comment]
Hmm, OK...can you run the following command in powershell and post back with the output?

`Get-StartApps | Select-String -Pattern "node.exe"`

**Comment by sgehrman** [comment]
@{Name=Node.js; AppID={6D809377-6AF0-444B-8957-A3773F02200E}\nodejs\node.exe}

**Comment by RoccoC** [comment]
Thanks for the quick reply.

This is what I am expecting, must be something else going on. I will look into how notifications work on Windows to see what I can find out.

**Comment by RoccoC** [comment]
OK! I am hoping my latest commit (df8e499104afbe0c199fd76c71435ea35d701d78) has fixed this issue for those on Windows build 1709.

Seems that prior to this Windows build there was a bug/loophole where any app could generate notifications, rather than known/installed apps (there are several posts around the interwebs describing this, e.g. https://stackoverflow.com/a/46817674/181483). The fix I've decided to implement entails ensuring that the SnoreToast executable (which node-notifier depends on to generate Windows notifications) has an appID, and then using that for the notifications. The downside is that each notification will be suffixed with "SnoreToast", but it at least works. :) If I come up with a better way I will definitely revisit.

Let me know if you have further issues! ;)

**Comment by RoccoC** [comment]
FYI, the fix is in webpack-build-notifier@0.1.21 which is now published to the npm registry.
