### ISSUE TITLE
Error when installing SnoreToast AppID

### ISSUE THREAD

**Issue by atdiff** [RoccoC/webpack-build-notifier#29]
I get the following error when webpack starts up related to the build notifier.  Everything still ends up working but it throws the error at the beginning.

```
An error occurred while attempting to install the SnoreToast AppID! { Error: Command failed: C:\myProject\node_modules\node-notifier\vendor\snoreToast\SnoreToast.exe -appID Snore.DesktopToasts -install SnoreToast.lnk C:\myProject\node_modules\node-notifier\vendor\snoreToast\SnoreToast.exe Snore.DesktopToasts
    at checkExecSyncError (child_process.js:596:11)
    at Object.execFileSync (child_process.js:614:13)
    at Object.<anonymous> (C:\myProject\node_modules\webpack-build-notifier\index.js:21:12)
    at Module._compile (C:\myProject\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (C:\myProject\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\myProject\webpack.config.js:4:36)
    at Module._compile (C:\myProject\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (C:\myProject\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\myProject\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (C:\myProject\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at C:\myProject\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\myProject\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (C:\myProject\node_modules\webpack-cli\bin\webpack.js:240:39)
    at Object.parse (C:\myProject\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
    at C:\myProject\node_modules\webpack-cli\bin\webpack.js:218:8
    at Object.<anonymous> (C:\myProject\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
```

**Comment by RoccoC** [comment]
Thanks for the report. Can you confirm which OS and version you are using?

**Comment by atdiff** [comment]
Windows 7

**Comment by RoccoC** [comment]
@atdiff, can you please see if this is still reproducible in the latest version of webpack-build-notifier (0.1.28)? This version updates to node-notifier@5.2.1, which I am hoping fixes the problem. Thanks!

**Comment by atdiff** [comment]
Unfortunately the error still gets thrown in the log even though the notifier ultimately ends up working.

**Comment by RoccoC** [comment]
Strange, must be specific to the build of Win7 you are running. If you send over the version/build number I can try and reproduce on my end. Reopening.

**Comment by jpmnteiro** [comment]
Can confirm the issue.

- webpack-build-notifier version 0.1.29
- Windows 7 Pro SP1 (version 6.1.7601.65536)

**Comment by 9deepan9** [comment]
I too face the same issue (An error occurred while attempting to install the SnoreToast AppID!): 
  -  "webpack-build-notifier": "0.1.28"
  -  Windows 7 Enterprise

Thanks.
