### ISSUE TITLE
Error in plugin??

### ISSUE THREAD

**Issue by mikeerickson** [RoccoC/webpack-build-notifier#6]
I am not sure if this is your error, or some other outside configuration.   

```
  Building [=================== ] 95% (9.5 seconds)/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-build-notifier/index.js:111
        msg = error.module.rawRequest + '\n' + error.error.replace(error.module.resource, '');
                                                           ^

TypeError: error.error.replace is not a function
    at WebpackBuildNotifierPlugin.onCompilationDone (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack-build-notifier/index.js:111:60)
    at Compiler.applyPlugins (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/tapable/lib/Tapable.js:26:37)
    at Compiler.<anonymous> (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack/lib/Compiler.js:193:12)
    at Compiler.emitRecords (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.next (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/copy-webpack-plugin/dist/index.js:190:13)
    at Compiler.applyPluginsAsync (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.afterEmit (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/webpack/lib/Compiler.js:267:14)
    at /Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/async/lib/async.js:52:16
    at done (/Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/async/lib/async.js:246:17)
    at /Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/async/lib/async.js:44:16
    at /Users/mikee/Documents/Projects/dev/angular/angular-sandbox/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by RoccoC** [comment]
Yep, looks like a bug introduced in the last commit. I'll get it fixed. Thanks.

**Comment by mikeerickson** [comment]
10/4 have fun :)

**Comment by RoccoC** [comment]
Fixed in v 0.1.11.

**Comment by mikeerickson** [comment]
Works fabulously again 💯

**Comment by hulkish** [comment]
I'm still seeing this issue in 0.1.11:

```bash
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack: wait until bundle finished: /mypage
 95% emit/Users/myuser/repos/myproject/node_modules/webpack-build-notifier/index.js:111
        msg = error.module.rawRequest + '\n' + (error.message ? error.message.replace(error.module.resource, '') : '');
                          ^

TypeError: Cannot read property 'rawRequest' of undefined
    at WebpackBuildNotifierPlugin.onCompilationDone (/Users/myuser/repos/myproject/node_modules/webpack-build-notifier/index.js:111:27)
    at Compiler.applyPlugins (/Users/myuser/repos/myproject/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/myuser/repos/myproject/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/myuser/repos/myproject/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/myuser/repos/myproject/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/myuser/repos/myproject/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/myuser/repos/myproject/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.next (/Users/myuser/repos/myproject/node_modules/tapable/lib/Tapable.js:67:11)
    at /Users/myuser/repos/myproject/node_modules/assets-webpack-plugin/index.js:82:9
    at /Users/myuser/repos/myproject/node_modules/assets-webpack-plugin/lib/output/createQueuedWriter.js:15:7
    at /Users/myuser/repos/myproject/node_modules/assets-webpack-plugin/lib/output/createOutputWriter.js:50:13
    at /Users/myuser/repos/myproject/node_modules/graceful-fs/graceful-fs.js:43:10
```

**Comment by RoccoC** [comment]
@hulkish , thanks for the PR. I've merged it and also added a couple more null checks. Feel free to update to v0.1.12 and open a new issue if you find anything else. Thanks!

**Comment by hulkish** [comment]
np!
